apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: stocker
  namespace: demo
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          labels:
            demo: stocker
        spec:
          container:
            image: gcr.io/s9-demo/myevents:latest
            imagePullPolicy: Always
            env:
            - name: RELEASE
              value: "v0.1.1"
            - name: GCP_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: project