apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: redis-queue-source
  namespace: demo
  labels:
    source: redis
spec:
  image: gcr.io/s9-demo/kres:latest
  imagePullPolicy: Always
  env:
  - name: RELEASE
    value: "v0.1.9"
  - name: REDIS_HOST
    value: "redis.demo.svc.cluster.local:6379"
  - name: REDIS_QUEUE
    value: "events"
  - name: REDIS_PASS
    valueFrom:
      secretKeyRef:
        name: redis-secrets
        key: REDIS_PASS
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: events
    namespace: demo